// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/manifest.dart';
import 'api/qr.dart';
import 'api/transfer.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    api.crateApiTransferInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 251598326;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_deopti_downloader',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  ManifestPayload? crateApiManifestDecodeManifest({required List<int> bytes});

  ManifestInfo? crateApiTransferDecodeManifestFfi({required List<int> bytes});

  int crateApiTransferDefaultFrameSize();

  Uint8List crateApiManifestEncodeManifest({required ManifestPayload payload});

  bool crateApiTransferEncryptionSupported();

  bool crateApiTransferFitsInOneStream({
    required int payloadLen,
    required int frameBytes,
  });

  double crateApiTransferFountainOverhead();

  Uint32List crateApiTransferFrameSizeOptions();

  void crateApiTransferInitApp();

  int crateApiTransferMaxFileBytes();

  PackedFileData crateApiTransferPackFileEncryptedFfi({
    required String name,
    required String mimeType,
    required List<int> bytes,
    required String password,
  });

  PackedFileData crateApiTransferPackFileFfi({
    required String name,
    required String mimeType,
    required List<int> bytes,
  });

  Uint8List? crateApiQrQrDecodeGray({
    required List<int> gray,
    required int width,
    required int height,
    int? maxScanDim,
  });

  Uint8List? crateApiQrQrDecodeRgba({
    required List<int> rgba,
    required int width,
    required int height,
    int? maxScanDim,
  });

  QrMatrix crateApiQrQrEncode({required List<int> data});

  QrMatrix crateApiTransferQrEncodeFrame({required List<int> bytes});

  int? crateApiQrQrVersionFor({required BigInt frameBytes});

  ReceiverSession crateApiTransferReceiverCreate();

  ReceiverOutcome crateApiTransferReceiverPush({
    required ReceiverSession session,
    required List<int> frameBytes,
  });

  ReceiverOutcome crateApiTransferReceiverState({
    required ReceiverSession session,
  });

  bool crateApiTransferRunSelfTest();

  SenderSession crateApiTransferSenderCreate({
    required List<int> container,
    required int frameBytes,
    int? sessionId,
  });

  SenderInfo crateApiTransferSenderInfo({required SenderSession session});

  SenderFrame crateApiTransferSenderNext({required SenderSession session});

  SenderFrameQr crateApiTransferSenderNextQr({required SenderSession session});

  Uint8List crateApiTransferSessionManifestBytes({
    required SenderSession session,
  });

  QrMatrix crateApiTransferSessionManifestQr({required SenderSession session});

  int? crateApiTransferSmallestSufficientFrameSizeFor({
    required int payloadLen,
  });

  int? crateApiTransferSourceBlockCountFor({
    required int payloadLen,
    required int frameBytes,
  });

  OpticalFileData crateApiTransferUnpackFileFfi({required List<int> container});

  OpticalFileData crateApiTransferUnpackFileWithPasswordFfi({
    required List<int> container,
    required String password,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ReceiverSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ReceiverSession;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ReceiverSessionPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SenderSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SenderSession;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SenderSessionPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  ManifestPayload? crateApiManifestDecodeManifest({required List<int> bytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_manifest_payload,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiManifestDecodeManifestConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiManifestDecodeManifestConstMeta =>
      const TaskConstMeta(debugName: "decode_manifest", argNames: ["bytes"]);

  @override
  ManifestInfo? crateApiTransferDecodeManifestFfi({required List<int> bytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_manifest_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTransferDecodeManifestFfiConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferDecodeManifestFfiConstMeta =>
      const TaskConstMeta(
        debugName: "decode_manifest_ffi",
        argNames: ["bytes"],
      );

  @override
  int crateApiTransferDefaultFrameSize() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTransferDefaultFrameSizeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferDefaultFrameSizeConstMeta =>
      const TaskConstMeta(debugName: "default_frame_size", argNames: []);

  @override
  Uint8List crateApiManifestEncodeManifest({required ManifestPayload payload}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_manifest_payload(payload, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiManifestEncodeManifestConstMeta,
        argValues: [payload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiManifestEncodeManifestConstMeta =>
      const TaskConstMeta(debugName: "encode_manifest", argNames: ["payload"]);

  @override
  bool crateApiTransferEncryptionSupported() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTransferEncryptionSupportedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferEncryptionSupportedConstMeta =>
      const TaskConstMeta(debugName: "encryption_supported", argNames: []);

  @override
  bool crateApiTransferFitsInOneStream({
    required int payloadLen,
    required int frameBytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(payloadLen, serializer);
          sse_encode_u_32(frameBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTransferFitsInOneStreamConstMeta,
        argValues: [payloadLen, frameBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferFitsInOneStreamConstMeta =>
      const TaskConstMeta(
        debugName: "fits_in_one_stream",
        argNames: ["payloadLen", "frameBytes"],
      );

  @override
  double crateApiTransferFountainOverhead() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTransferFountainOverheadConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferFountainOverheadConstMeta =>
      const TaskConstMeta(debugName: "fountain_overhead", argNames: []);

  @override
  Uint32List crateApiTransferFrameSizeOptions() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_32_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTransferFrameSizeOptionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferFrameSizeOptionsConstMeta =>
      const TaskConstMeta(debugName: "frame_size_options", argNames: []);

  @override
  void crateApiTransferInitApp() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTransferInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  int crateApiTransferMaxFileBytes() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTransferMaxFileBytesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferMaxFileBytesConstMeta =>
      const TaskConstMeta(debugName: "max_file_bytes", argNames: []);

  @override
  PackedFileData crateApiTransferPackFileEncryptedFfi({
    required String name,
    required String mimeType,
    required List<int> bytes,
    required String password,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(mimeType, serializer);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_String(password, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_packed_file_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTransferPackFileEncryptedFfiConstMeta,
        argValues: [name, mimeType, bytes, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferPackFileEncryptedFfiConstMeta =>
      const TaskConstMeta(
        debugName: "pack_file_encrypted_ffi",
        argNames: ["name", "mimeType", "bytes", "password"],
      );

  @override
  PackedFileData crateApiTransferPackFileFfi({
    required String name,
    required String mimeType,
    required List<int> bytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(mimeType, serializer);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_packed_file_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTransferPackFileFfiConstMeta,
        argValues: [name, mimeType, bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferPackFileFfiConstMeta =>
      const TaskConstMeta(
        debugName: "pack_file_ffi",
        argNames: ["name", "mimeType", "bytes"],
      );

  @override
  Uint8List? crateApiQrQrDecodeGray({
    required List<int> gray,
    required int width,
    required int height,
    int? maxScanDim,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(gray, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_opt_box_autoadd_u_32(maxScanDim, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiQrQrDecodeGrayConstMeta,
        argValues: [gray, width, height, maxScanDim],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQrQrDecodeGrayConstMeta => const TaskConstMeta(
    debugName: "qr_decode_gray",
    argNames: ["gray", "width", "height", "maxScanDim"],
  );

  @override
  Uint8List? crateApiQrQrDecodeRgba({
    required List<int> rgba,
    required int width,
    required int height,
    int? maxScanDim,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(rgba, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_opt_box_autoadd_u_32(maxScanDim, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiQrQrDecodeRgbaConstMeta,
        argValues: [rgba, width, height, maxScanDim],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQrQrDecodeRgbaConstMeta => const TaskConstMeta(
    debugName: "qr_decode_rgba",
    argNames: ["rgba", "width", "height", "maxScanDim"],
  );

  @override
  QrMatrix crateApiQrQrEncode({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_qr_matrix,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiQrQrEncodeConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQrQrEncodeConstMeta =>
      const TaskConstMeta(debugName: "qr_encode", argNames: ["data"]);

  @override
  QrMatrix crateApiTransferQrEncodeFrame({required List<int> bytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_qr_matrix,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTransferQrEncodeFrameConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferQrEncodeFrameConstMeta =>
      const TaskConstMeta(debugName: "qr_encode_frame", argNames: ["bytes"]);

  @override
  int? crateApiQrQrVersionFor({required BigInt frameBytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_usize(frameBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_u_8,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQrQrVersionForConstMeta,
        argValues: [frameBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQrQrVersionForConstMeta => const TaskConstMeta(
    debugName: "qr_version_for",
    argNames: ["frameBytes"],
  );

  @override
  ReceiverSession crateApiTransferReceiverCreate() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReceiverSession,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTransferReceiverCreateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferReceiverCreateConstMeta =>
      const TaskConstMeta(debugName: "receiver_create", argNames: []);

  @override
  ReceiverOutcome crateApiTransferReceiverPush({
    required ReceiverSession session,
    required List<int> frameBytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReceiverSession(
            session,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(frameBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_receiver_outcome,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTransferReceiverPushConstMeta,
        argValues: [session, frameBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferReceiverPushConstMeta =>
      const TaskConstMeta(
        debugName: "receiver_push",
        argNames: ["session", "frameBytes"],
      );

  @override
  ReceiverOutcome crateApiTransferReceiverState({
    required ReceiverSession session,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReceiverSession(
            session,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_receiver_outcome,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTransferReceiverStateConstMeta,
        argValues: [session],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferReceiverStateConstMeta =>
      const TaskConstMeta(debugName: "receiver_state", argNames: ["session"]);

  @override
  bool crateApiTransferRunSelfTest() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTransferRunSelfTestConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferRunSelfTestConstMeta =>
      const TaskConstMeta(debugName: "run_self_test", argNames: []);

  @override
  SenderSession crateApiTransferSenderCreate({
    required List<int> container,
    required int frameBytes,
    int? sessionId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(container, serializer);
          sse_encode_u_32(frameBytes, serializer);
          sse_encode_opt_box_autoadd_u_16(sessionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderSession,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTransferSenderCreateConstMeta,
        argValues: [container, frameBytes, sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferSenderCreateConstMeta =>
      const TaskConstMeta(
        debugName: "sender_create",
        argNames: ["container", "frameBytes", "sessionId"],
      );

  @override
  SenderInfo crateApiTransferSenderInfo({required SenderSession session}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderSession(
            session,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sender_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTransferSenderInfoConstMeta,
        argValues: [session],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferSenderInfoConstMeta =>
      const TaskConstMeta(debugName: "sender_info", argNames: ["session"]);

  @override
  SenderFrame crateApiTransferSenderNext({required SenderSession session}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderSession(
            session,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sender_frame,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTransferSenderNextConstMeta,
        argValues: [session],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferSenderNextConstMeta =>
      const TaskConstMeta(debugName: "sender_next", argNames: ["session"]);

  @override
  SenderFrameQr crateApiTransferSenderNextQr({required SenderSession session}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderSession(
            session,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sender_frame_qr,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTransferSenderNextQrConstMeta,
        argValues: [session],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferSenderNextQrConstMeta =>
      const TaskConstMeta(debugName: "sender_next_qr", argNames: ["session"]);

  @override
  Uint8List crateApiTransferSessionManifestBytes({
    required SenderSession session,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderSession(
            session,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTransferSessionManifestBytesConstMeta,
        argValues: [session],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferSessionManifestBytesConstMeta =>
      const TaskConstMeta(
        debugName: "session_manifest_bytes",
        argNames: ["session"],
      );

  @override
  QrMatrix crateApiTransferSessionManifestQr({required SenderSession session}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderSession(
            session,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_qr_matrix,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTransferSessionManifestQrConstMeta,
        argValues: [session],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferSessionManifestQrConstMeta =>
      const TaskConstMeta(
        debugName: "session_manifest_qr",
        argNames: ["session"],
      );

  @override
  int? crateApiTransferSmallestSufficientFrameSizeFor({
    required int payloadLen,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(payloadLen, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTransferSmallestSufficientFrameSizeForConstMeta,
        argValues: [payloadLen],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferSmallestSufficientFrameSizeForConstMeta =>
      const TaskConstMeta(
        debugName: "smallest_sufficient_frame_size_for",
        argNames: ["payloadLen"],
      );

  @override
  int? crateApiTransferSourceBlockCountFor({
    required int payloadLen,
    required int frameBytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(payloadLen, serializer);
          sse_encode_u_32(frameBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTransferSourceBlockCountForConstMeta,
        argValues: [payloadLen, frameBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferSourceBlockCountForConstMeta =>
      const TaskConstMeta(
        debugName: "source_block_count_for",
        argNames: ["payloadLen", "frameBytes"],
      );

  @override
  OpticalFileData crateApiTransferUnpackFileFfi({
    required List<int> container,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(container, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_optical_file_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTransferUnpackFileFfiConstMeta,
        argValues: [container],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferUnpackFileFfiConstMeta =>
      const TaskConstMeta(
        debugName: "unpack_file_ffi",
        argNames: ["container"],
      );

  @override
  OpticalFileData crateApiTransferUnpackFileWithPasswordFfi({
    required List<int> container,
    required String password,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(container, serializer);
          sse_encode_String(password, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_optical_file_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTransferUnpackFileWithPasswordFfiConstMeta,
        argValues: [container, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransferUnpackFileWithPasswordFfiConstMeta =>
      const TaskConstMeta(
        debugName: "unpack_file_with_password_ffi",
        argNames: ["container", "password"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ReceiverSession => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReceiverSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ReceiverSession => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReceiverSession;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SenderSession => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SenderSession => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderSession;

  @protected
  ReceiverSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReceiverSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReceiverSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SenderSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SenderSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ReceiverSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReceiverSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReceiverSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SenderSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SenderSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ReceiverSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReceiverSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReceiverSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SenderSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SenderSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ManifestInfo dco_decode_box_autoadd_manifest_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_manifest_info(raw);
  }

  @protected
  ManifestPayload dco_decode_box_autoadd_manifest_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_manifest_payload(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  ManifestInfo dco_decode_manifest_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return ManifestInfo(
      sessionId: dco_decode_u_16(arr[0]),
      k: dco_decode_u_16(arr[1]),
      blockLen: dco_decode_u_16(arr[2]),
      totalLen: dco_decode_u_32(arr[3]),
      frameBytes: dco_decode_u_32(arr[4]),
      qrVersion: dco_decode_u_8(arr[5]),
      mode: dco_decode_String(arr[6]),
      fileName: dco_decode_String(arr[7]),
      mimeType: dco_decode_String(arr[8]),
      encrypted: dco_decode_bool(arr[9]),
    );
  }

  @protected
  ManifestPayload dco_decode_manifest_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return ManifestPayload(
      version: dco_decode_u_8(arr[0]),
      sessionId: dco_decode_u_16(arr[1]),
      k: dco_decode_u_16(arr[2]),
      blockLen: dco_decode_u_16(arr[3]),
      totalLen: dco_decode_u_32(arr[4]),
      frameBytes: dco_decode_u_16(arr[5]),
      qrVersion: dco_decode_u_8(arr[6]),
      mode: dco_decode_u_8(arr[7]),
      encrypted: dco_decode_bool(arr[8]),
      fileName: dco_decode_String(arr[9]),
      mimeType: dco_decode_String(arr[10]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ManifestInfo? dco_decode_opt_box_autoadd_manifest_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_manifest_info(raw);
  }

  @protected
  ManifestPayload? dco_decode_opt_box_autoadd_manifest_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_manifest_payload(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_16(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_8(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  OpticalFileData dco_decode_optical_file_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return OpticalFileData(
      name: dco_decode_String(arr[0]),
      mimeType: dco_decode_String(arr[1]),
      bytes: dco_decode_list_prim_u_8_strict(arr[2]),
      digest: dco_decode_list_prim_u_8_strict(arr[3]),
      compression: dco_decode_String(arr[4]),
      encrypted: dco_decode_bool(arr[5]),
      transmittedSize: dco_decode_u_32(arr[6]),
    );
  }

  @protected
  PackedFileData dco_decode_packed_file_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PackedFileData(
      container: dco_decode_list_prim_u_8_strict(arr[0]),
      originalSize: dco_decode_u_32(arr[1]),
      transmittedSize: dco_decode_u_32(arr[2]),
      compression: dco_decode_String(arr[3]),
      encrypted: dco_decode_bool(arr[4]),
    );
  }

  @protected
  PushStatus dco_decode_push_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PushStatus.values[raw as int];
  }

  @protected
  QrMatrix dco_decode_qr_matrix(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return QrMatrix(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      cells: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  ReceiverOutcome dco_decode_receiver_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ReceiverOutcome(
      status: dco_decode_push_status(arr[0]),
      container: dco_decode_opt_list_prim_u_8_strict(arr[1]),
      collected: dco_decode_u_32(arr[2]),
      k: dco_decode_opt_box_autoadd_u_16(arr[3]),
      blockLen: dco_decode_opt_box_autoadd_u_16(arr[4]),
      totalLen: dco_decode_opt_box_autoadd_u_32(arr[5]),
      sessionId: dco_decode_opt_box_autoadd_u_16(arr[6]),
      mode: dco_decode_opt_String(arr[7]),
      delivered: dco_decode_bool(arr[8]),
    );
  }

  @protected
  SenderFrame dco_decode_sender_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SenderFrame(
      seq: dco_decode_u_32(arr[0]),
      bytes: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  SenderFrameQr dco_decode_sender_frame_qr(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SenderFrameQr(
      frame: dco_decode_sender_frame(arr[0]),
      qr: dco_decode_qr_matrix(arr[1]),
    );
  }

  @protected
  SenderInfo dco_decode_sender_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SenderInfo(
      sessionId: dco_decode_u_16(arr[0]),
      k: dco_decode_u_16(arr[1]),
      blockLen: dco_decode_u_16(arr[2]),
      totalLen: dco_decode_u_32(arr[3]),
      mode: dco_decode_String(arr[4]),
      frameBytes: dco_decode_u_32(arr[5]),
      qrVersion: dco_decode_u_8(arr[6]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  ReceiverSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReceiverSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ReceiverSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SenderSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SenderSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ReceiverSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReceiverSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ReceiverSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SenderSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SenderSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ReceiverSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReceiverSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ReceiverSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SenderSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SenderSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ManifestInfo sse_decode_box_autoadd_manifest_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_manifest_info(deserializer));
  }

  @protected
  ManifestPayload sse_decode_box_autoadd_manifest_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_manifest_payload(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_16(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_8(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  ManifestInfo sse_decode_manifest_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_u_16(deserializer);
    var var_k = sse_decode_u_16(deserializer);
    var var_blockLen = sse_decode_u_16(deserializer);
    var var_totalLen = sse_decode_u_32(deserializer);
    var var_frameBytes = sse_decode_u_32(deserializer);
    var var_qrVersion = sse_decode_u_8(deserializer);
    var var_mode = sse_decode_String(deserializer);
    var var_fileName = sse_decode_String(deserializer);
    var var_mimeType = sse_decode_String(deserializer);
    var var_encrypted = sse_decode_bool(deserializer);
    return ManifestInfo(
      sessionId: var_sessionId,
      k: var_k,
      blockLen: var_blockLen,
      totalLen: var_totalLen,
      frameBytes: var_frameBytes,
      qrVersion: var_qrVersion,
      mode: var_mode,
      fileName: var_fileName,
      mimeType: var_mimeType,
      encrypted: var_encrypted,
    );
  }

  @protected
  ManifestPayload sse_decode_manifest_payload(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_version = sse_decode_u_8(deserializer);
    var var_sessionId = sse_decode_u_16(deserializer);
    var var_k = sse_decode_u_16(deserializer);
    var var_blockLen = sse_decode_u_16(deserializer);
    var var_totalLen = sse_decode_u_32(deserializer);
    var var_frameBytes = sse_decode_u_16(deserializer);
    var var_qrVersion = sse_decode_u_8(deserializer);
    var var_mode = sse_decode_u_8(deserializer);
    var var_encrypted = sse_decode_bool(deserializer);
    var var_fileName = sse_decode_String(deserializer);
    var var_mimeType = sse_decode_String(deserializer);
    return ManifestPayload(
      version: var_version,
      sessionId: var_sessionId,
      k: var_k,
      blockLen: var_blockLen,
      totalLen: var_totalLen,
      frameBytes: var_frameBytes,
      qrVersion: var_qrVersion,
      mode: var_mode,
      encrypted: var_encrypted,
      fileName: var_fileName,
      mimeType: var_mimeType,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ManifestInfo? sse_decode_opt_box_autoadd_manifest_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_manifest_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ManifestPayload? sse_decode_opt_box_autoadd_manifest_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_manifest_payload(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_8(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  OpticalFileData sse_decode_optical_file_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_mimeType = sse_decode_String(deserializer);
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_digest = sse_decode_list_prim_u_8_strict(deserializer);
    var var_compression = sse_decode_String(deserializer);
    var var_encrypted = sse_decode_bool(deserializer);
    var var_transmittedSize = sse_decode_u_32(deserializer);
    return OpticalFileData(
      name: var_name,
      mimeType: var_mimeType,
      bytes: var_bytes,
      digest: var_digest,
      compression: var_compression,
      encrypted: var_encrypted,
      transmittedSize: var_transmittedSize,
    );
  }

  @protected
  PackedFileData sse_decode_packed_file_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_container = sse_decode_list_prim_u_8_strict(deserializer);
    var var_originalSize = sse_decode_u_32(deserializer);
    var var_transmittedSize = sse_decode_u_32(deserializer);
    var var_compression = sse_decode_String(deserializer);
    var var_encrypted = sse_decode_bool(deserializer);
    return PackedFileData(
      container: var_container,
      originalSize: var_originalSize,
      transmittedSize: var_transmittedSize,
      compression: var_compression,
      encrypted: var_encrypted,
    );
  }

  @protected
  PushStatus sse_decode_push_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PushStatus.values[inner];
  }

  @protected
  QrMatrix sse_decode_qr_matrix(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_cells = sse_decode_list_prim_u_8_strict(deserializer);
    return QrMatrix(width: var_width, height: var_height, cells: var_cells);
  }

  @protected
  ReceiverOutcome sse_decode_receiver_outcome(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_push_status(deserializer);
    var var_container = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_collected = sse_decode_u_32(deserializer);
    var var_k = sse_decode_opt_box_autoadd_u_16(deserializer);
    var var_blockLen = sse_decode_opt_box_autoadd_u_16(deserializer);
    var var_totalLen = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_sessionId = sse_decode_opt_box_autoadd_u_16(deserializer);
    var var_mode = sse_decode_opt_String(deserializer);
    var var_delivered = sse_decode_bool(deserializer);
    return ReceiverOutcome(
      status: var_status,
      container: var_container,
      collected: var_collected,
      k: var_k,
      blockLen: var_blockLen,
      totalLen: var_totalLen,
      sessionId: var_sessionId,
      mode: var_mode,
      delivered: var_delivered,
    );
  }

  @protected
  SenderFrame sse_decode_sender_frame(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_seq = sse_decode_u_32(deserializer);
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    return SenderFrame(seq: var_seq, bytes: var_bytes);
  }

  @protected
  SenderFrameQr sse_decode_sender_frame_qr(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_frame = sse_decode_sender_frame(deserializer);
    var var_qr = sse_decode_qr_matrix(deserializer);
    return SenderFrameQr(frame: var_frame, qr: var_qr);
  }

  @protected
  SenderInfo sse_decode_sender_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_u_16(deserializer);
    var var_k = sse_decode_u_16(deserializer);
    var var_blockLen = sse_decode_u_16(deserializer);
    var var_totalLen = sse_decode_u_32(deserializer);
    var var_mode = sse_decode_String(deserializer);
    var var_frameBytes = sse_decode_u_32(deserializer);
    var var_qrVersion = sse_decode_u_8(deserializer);
    return SenderInfo(
      sessionId: var_sessionId,
      k: var_k,
      blockLen: var_blockLen,
      totalLen: var_totalLen,
      mode: var_mode,
      frameBytes: var_frameBytes,
      qrVersion: var_qrVersion,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReceiverSession(
    ReceiverSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ReceiverSessionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderSession(
    SenderSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SenderSessionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReceiverSession(
    ReceiverSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ReceiverSessionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderSession(
    SenderSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SenderSessionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReceiverSession(
    ReceiverSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ReceiverSessionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSenderSession(
    SenderSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SenderSessionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_manifest_info(
    ManifestInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_manifest_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_manifest_payload(
    ManifestPayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_manifest_payload(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_manifest_info(ManifestInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.sessionId, serializer);
    sse_encode_u_16(self.k, serializer);
    sse_encode_u_16(self.blockLen, serializer);
    sse_encode_u_32(self.totalLen, serializer);
    sse_encode_u_32(self.frameBytes, serializer);
    sse_encode_u_8(self.qrVersion, serializer);
    sse_encode_String(self.mode, serializer);
    sse_encode_String(self.fileName, serializer);
    sse_encode_String(self.mimeType, serializer);
    sse_encode_bool(self.encrypted, serializer);
  }

  @protected
  void sse_encode_manifest_payload(
    ManifestPayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.version, serializer);
    sse_encode_u_16(self.sessionId, serializer);
    sse_encode_u_16(self.k, serializer);
    sse_encode_u_16(self.blockLen, serializer);
    sse_encode_u_32(self.totalLen, serializer);
    sse_encode_u_16(self.frameBytes, serializer);
    sse_encode_u_8(self.qrVersion, serializer);
    sse_encode_u_8(self.mode, serializer);
    sse_encode_bool(self.encrypted, serializer);
    sse_encode_String(self.fileName, serializer);
    sse_encode_String(self.mimeType, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_manifest_info(
    ManifestInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_manifest_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_manifest_payload(
    ManifestPayload? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_manifest_payload(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_8(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_optical_file_data(
    OpticalFileData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.mimeType, serializer);
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
    sse_encode_list_prim_u_8_strict(self.digest, serializer);
    sse_encode_String(self.compression, serializer);
    sse_encode_bool(self.encrypted, serializer);
    sse_encode_u_32(self.transmittedSize, serializer);
  }

  @protected
  void sse_encode_packed_file_data(
    PackedFileData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.container, serializer);
    sse_encode_u_32(self.originalSize, serializer);
    sse_encode_u_32(self.transmittedSize, serializer);
    sse_encode_String(self.compression, serializer);
    sse_encode_bool(self.encrypted, serializer);
  }

  @protected
  void sse_encode_push_status(PushStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_qr_matrix(QrMatrix self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.cells, serializer);
  }

  @protected
  void sse_encode_receiver_outcome(
    ReceiverOutcome self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_push_status(self.status, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.container, serializer);
    sse_encode_u_32(self.collected, serializer);
    sse_encode_opt_box_autoadd_u_16(self.k, serializer);
    sse_encode_opt_box_autoadd_u_16(self.blockLen, serializer);
    sse_encode_opt_box_autoadd_u_32(self.totalLen, serializer);
    sse_encode_opt_box_autoadd_u_16(self.sessionId, serializer);
    sse_encode_opt_String(self.mode, serializer);
    sse_encode_bool(self.delivered, serializer);
  }

  @protected
  void sse_encode_sender_frame(SenderFrame self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.seq, serializer);
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
  }

  @protected
  void sse_encode_sender_frame_qr(
    SenderFrameQr self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_sender_frame(self.frame, serializer);
    sse_encode_qr_matrix(self.qr, serializer);
  }

  @protected
  void sse_encode_sender_info(SenderInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.sessionId, serializer);
    sse_encode_u_16(self.k, serializer);
    sse_encode_u_16(self.blockLen, serializer);
    sse_encode_u_32(self.totalLen, serializer);
    sse_encode_String(self.mode, serializer);
    sse_encode_u_32(self.frameBytes, serializer);
    sse_encode_u_8(self.qrVersion, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class ReceiverSessionImpl extends RustOpaque implements ReceiverSession {
  // Not to be used by end users
  ReceiverSessionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ReceiverSessionImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ReceiverSession,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ReceiverSession,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ReceiverSessionPtr,
  );
}

@sealed
class SenderSessionImpl extends RustOpaque implements SenderSession {
  // Not to be used by end users
  SenderSessionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SenderSessionImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_SenderSession,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_SenderSession,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_SenderSessionPtr,
  );
}
