// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ManifestMode`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// Encode a manifest: fixed 4-byte magic followed by the bounded rustbinary
/// payload. Returns an error (never panics) when the payload is too large.
Uint8List encodeManifest({required ManifestPayload payload}) =>
    RustLib.instance.api.crateApiManifestEncodeManifest(payload: payload);

/// Decode a manifest from raw bytes.
///
/// Returns `Ok(None)` when the magic does not match (i.e. the bytes are not a
/// manifest — likely a fountain frame), and `Err` for a malformed manifest so
/// callers can decide whether to treat it as an erasure.
ManifestPayload? decodeManifest({required List<int> bytes}) =>
    RustLib.instance.api.crateApiManifestDecodeManifest(bytes: bytes);

/// The serialized payload of a session manifest.
class ManifestPayload {
  /// Schema version (`MANIFEST_VERSION`); receivers ignore unknown versions.
  final int version;
  final int sessionId;

  /// Source block count.
  final int k;

  /// Payload bytes per fountain frame (frame size minus the 25-byte header).
  final int blockLen;

  /// Protected container length in bytes.
  final int totalLen;

  /// Total bytes per frame on the wire (header + block).
  final int frameBytes;
  final int qrVersion;
  final int mode;
  final bool encrypted;
  final String fileName;
  final String mimeType;

  const ManifestPayload({
    required this.version,
    required this.sessionId,
    required this.k,
    required this.blockLen,
    required this.totalLen,
    required this.frameBytes,
    required this.qrVersion,
    required this.mode,
    required this.encrypted,
    required this.fileName,
    required this.mimeType,
  });

  @override
  int get hashCode =>
      version.hashCode ^
      sessionId.hashCode ^
      k.hashCode ^
      blockLen.hashCode ^
      totalLen.hashCode ^
      frameBytes.hashCode ^
      qrVersion.hashCode ^
      mode.hashCode ^
      encrypted.hashCode ^
      fileName.hashCode ^
      mimeType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ManifestPayload &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          sessionId == other.sessionId &&
          k == other.k &&
          blockLen == other.blockLen &&
          totalLen == other.totalLen &&
          frameBytes == other.frameBytes &&
          qrVersion == other.qrVersion &&
          mode == other.mode &&
          encrypted == other.encrypted &&
          fileName == other.fileName &&
          mimeType == other.mimeType;
}
