// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `decode_luma`, `downscale`

/// Smallest QR version (1..=40) whose ECC-L byte capacity holds `frame_bytes`,
/// or `None` when it does not fit in a Version-40 symbol.
int? qrVersionFor({required BigInt frameBytes}) =>
    RustLib.instance.api.crateApiQrQrVersionFor(frameBytes: frameBytes);

/// Encode raw bytes into a QR module matrix (ECC L, smallest fitting version).
QrMatrix qrEncode({required List<int> data}) =>
    RustLib.instance.api.crateApiQrQrEncode(data: data);

/// Decode a QR from a tight grayscale (luma8) buffer, optionally downscaled.
Uint8List? qrDecodeGray({
  required List<int> gray,
  required int width,
  required int height,
  int? maxScanDim,
}) => RustLib.instance.api.crateApiQrQrDecodeGray(
  gray: gray,
  width: width,
  height: height,
  maxScanDim: maxScanDim,
);

/// Decode a QR from an RGBA buffer, extracting luminance first.
Uint8List? qrDecodeRgba({
  required List<int> rgba,
  required int width,
  required int height,
  int? maxScanDim,
}) => RustLib.instance.api.crateApiQrQrDecodeRgba(
  rgba: rgba,
  width: width,
  height: height,
  maxScanDim: maxScanDim,
);
