// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `container_metadata`, `manifest_for`, `ot_error`, `random_u16`, `receiver_identity`, `to_file_data`, `to_manifest_info`, `to_packed_data`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ReceiverIdentity`, `ReceiverState`, `SenderState`

/// Whether authenticated encryption is compiled into this build.
///
/// Encryption needs `getrandom`, which is not available on the default
/// `wasm32-unknown-unknown` web build, so it is an opt-in Cargo feature there.
bool encryptionSupported() =>
    RustLib.instance.api.crateApiTransferEncryptionSupported();

/// The reference's 64 MiB file cap.
int maxFileBytes() => RustLib.instance.api.crateApiTransferMaxFileBytes();

/// Canonical frame sizes offered by the sender.
Uint32List frameSizeOptions() =>
    RustLib.instance.api.crateApiTransferFrameSizeOptions();

/// Default frame size (Version-40 QR, maximum throughput).
int defaultFrameSize() =>
    RustLib.instance.api.crateApiTransferDefaultFrameSize();

/// Source blocks a payload splits into at a given frame size.
int? sourceBlockCountFor({required int payloadLen, required int frameBytes}) =>
    RustLib.instance.api.crateApiTransferSourceBlockCountFor(
      payloadLen: payloadLen,
      frameBytes: frameBytes,
    );

/// Whether a payload fits a single stream at a given frame size.
bool fitsInOneStream({required int payloadLen, required int frameBytes}) =>
    RustLib.instance.api.crateApiTransferFitsInOneStream(
      payloadLen: payloadLen,
      frameBytes: frameBytes,
    );

/// The smallest canonical frame size that can carry `payload_len` bytes.
int? smallestSufficientFrameSizeFor({required int payloadLen}) => RustLib
    .instance
    .api
    .crateApiTransferSmallestSufficientFrameSizeFor(payloadLen: payloadLen);

/// Fountain redundancy factor: the receiver may need ~K × this many distinct
/// frames on a noisy channel. Used for progress estimation.
double fountainOverhead() =>
    RustLib.instance.api.crateApiTransferFountainOverhead();

/// Pack a file (name + MIME + bytes) into a DCF3 container.
PackedFileData packFileFfi({
  required String name,
  required String mimeType,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiTransferPackFileFfi(
  name: name,
  mimeType: mimeType,
  bytes: bytes,
);

/// Pack with optional password encryption (only in `encryption` builds).
PackedFileData packFileEncryptedFfi({
  required String name,
  required String mimeType,
  required List<int> bytes,
  required String password,
}) => RustLib.instance.api.crateApiTransferPackFileEncryptedFfi(
  name: name,
  mimeType: mimeType,
  bytes: bytes,
  password: password,
);

/// Recover the original file from a plain DCF3 container.
OpticalFileData unpackFileFfi({required List<int> container}) =>
    RustLib.instance.api.crateApiTransferUnpackFileFfi(container: container);

/// Recover a password-encrypted DCF3 container (only in `encryption` builds).
OpticalFileData unpackFileWithPasswordFfi({
  required List<int> container,
  required String password,
}) => RustLib.instance.api.crateApiTransferUnpackFileWithPasswordFfi(
  container: container,
  password: password,
);

/// Generate a fresh JRC judge keypair from the OS RNG (encryption builds).
///
/// The public key is shared with senders; the secret key stays with the
/// judge. On non-encryption builds (Web) this returns an error, mirroring
/// [`pack_file_encrypted_ffi`].
JudgeKeyPairData jrcKeygenFfi() =>
    RustLib.instance.api.crateApiTransferJrcKeygenFfi();

/// Pack a file for judge-recoverable optical transfer (encryption builds).
///
/// `judge_public_key` is the 32 raw bytes of the judge's X25519 public key.
/// The returned `envelope` is fed to the fountain sender exactly like a
/// normal DCF3 container. Co-receiving cameras see only the hiding
/// commitment and ciphertext; the judge recovers the file with
/// [`unpack_file_jrc_ffi`].
JrcPackedData packFileJrcFfi({
  required String name,
  required String mimeType,
  required List<int> bytes,
  required List<int> judgePublicKey,
}) => RustLib.instance.api.crateApiTransferPackFileJrcFfi(
  name: name,
  mimeType: mimeType,
  bytes: bytes,
  judgePublicKey: judgePublicKey,
);

/// Recover a file from a JRC envelope with the judge's secret key.
///
/// `judge_secret_key` is the 32 raw bytes of the judge's X25519 secret key.
/// The JRC binding check and the DCF3 digest both verify the recovered
/// container before any metadata is trusted.
OpticalFileData unpackFileJrcFfi({
  required List<int> envelope,
  required List<int> judgeSecretKey,
}) => RustLib.instance.api.crateApiTransferUnpackFileJrcFfi(
  envelope: envelope,
  judgeSecretKey: judgeSecretKey,
);

/// Run a full JRC round trip in-process: keygen → pack → judge recover.
/// Returns `true` on success; used by the app's diagnostics and by tests.
bool jrcSelfTest() => RustLib.instance.api.crateApiTransferJrcSelfTest();

/// Create a sending session for an already-packed container.
///
/// `frame_bytes` is the total on-the-wire frame size (header + block); the
/// session derives `block_len` from it. A fresh random `session_id` is picked
/// unless one is supplied (useful for deterministic tests).
SenderSession senderCreate({
  required List<int> container,
  required int frameBytes,
  int? sessionId,
}) => RustLib.instance.api.crateApiTransferSenderCreate(
  container: container,
  frameBytes: frameBytes,
  sessionId: sessionId,
);

/// Static facts about a sending session.
SenderInfo senderInfo({required SenderSession session}) =>
    RustLib.instance.api.crateApiTransferSenderInfo(session: session);

/// Emit the next fountain frame (wire bytes only).
SenderFrame senderNext({required SenderSession session}) =>
    RustLib.instance.api.crateApiTransferSenderNext(session: session);

/// Emit the next frame together with its QR matrix in one bridge call.
SenderFrameQr senderNextQr({required SenderSession session}) =>
    RustLib.instance.api.crateApiTransferSenderNextQr(session: session);

/// Build the session-manifest QR for a live sending session.
///
/// This is the *first* QR a receiver should scan: it carries the file name,
/// size and block layout so the receiving side can preview the transfer and
/// verify that the stream which locks on afterwards belongs to this session.
QrMatrix sessionManifestQr({required SenderSession session}) =>
    RustLib.instance.api.crateApiTransferSessionManifestQr(session: session);

/// Raw encoded session manifest for a live sending session (diagnostics and
/// tests). The QR variant is what the UI shows; this returns the wire bytes.
Uint8List sessionManifestBytes({required SenderSession session}) =>
    RustLib.instance.api.crateApiTransferSessionManifestBytes(session: session);

/// Decode raw bytes as a session manifest, if they are one.
///
/// Returns `Ok(None)` when the bytes are not a manifest (e.g. a fountain
/// frame) and `Err` for a malformed manifest, so callers can route decoded
/// QR payloads without a protocol dependency.
ManifestInfo? decodeManifestFfi({required List<int> bytes}) =>
    RustLib.instance.api.crateApiTransferDecodeManifestFfi(bytes: bytes);

/// Create a fresh receiving session.
ReceiverSession receiverCreate() =>
    RustLib.instance.api.crateApiTransferReceiverCreate();

/// Push one decoded frame into the receiver.
///
/// Corrupt frames are treated as erasures (the fountain absorbs them);
/// frames from a different stream cause an automatic re-lock so a restarted
/// sender is picked up immediately.
ReceiverOutcome receiverPush({
  required ReceiverSession session,
  required List<int> frameBytes,
}) => RustLib.instance.api.crateApiTransferReceiverPush(
  session: session,
  frameBytes: frameBytes,
);

/// Live state of the receiver (identity + progress), for UI refreshes.
ReceiverOutcome receiverState({required ReceiverSession session}) =>
    RustLib.instance.api.crateApiTransferReceiverState(session: session);

/// Run a full pack → send → receive → unpack round trip in-process.
/// Returns `true` on success; used by the app's diagnostics and by tests.
bool runSelfTest() => RustLib.instance.api.crateApiTransferRunSelfTest();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ReceiverSession>>
abstract class ReceiverSession implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SenderSession>>
abstract class SenderSession implements RustOpaqueInterface {}
