// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// A file packed for judge-recoverable optical transfer (JRC mode).
///
/// `envelope` is the serialized JRC transcript (`magic ‖ c ‖ aux`) that flows
/// through the fountain stream unchanged. Any camera pointed at the screen
/// sees only the hiding commitment and ciphertext; only the designated judge
/// (holding the matching secret key) recovers the original DCF3 container
/// with [`unpack_file_jrc_ffi`].
class JrcPackedData {
  final Uint8List envelope;
  final int originalSize;
  final int transmittedSize;

  const JrcPackedData({
    required this.envelope,
    required this.originalSize,
    required this.transmittedSize,
  });

  @override
  int get hashCode =>
      envelope.hashCode ^ originalSize.hashCode ^ transmittedSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JrcPackedData &&
          runtimeType == other.runtimeType &&
          envelope == other.envelope &&
          originalSize == other.originalSize &&
          transmittedSize == other.transmittedSize;
}

/// A freshly generated JRC judge keypair (32-byte X25519 keys).
///
/// The public key is meant to be shared (the sender commits against it); the
/// secret key is judge-only and must be kept safe by whoever may recover the
/// transfer. Both are serialized as raw 32-byte little-endian X25519 scalars.
class JudgeKeyPairData {
  /// 32 raw bytes of the judge public key (`ek`).
  final Uint8List publicKey;

  /// 32 raw bytes of the judge secret key (`dk`).
  final Uint8List secretKey;

  const JudgeKeyPairData({required this.publicKey, required this.secretKey});

  @override
  int get hashCode => publicKey.hashCode ^ secretKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JudgeKeyPairData &&
          runtimeType == other.runtimeType &&
          publicKey == other.publicKey &&
          secretKey == other.secretKey;
}

/// A decoded session manifest: the sender's metadata shown as the first QR
/// so the receiver can preview the transfer before any data frame arrives.
class ManifestInfo {
  final int sessionId;
  final int k;
  final int blockLen;
  final int totalLen;
  final int frameBytes;
  final int qrVersion;
  final String mode;
  final String fileName;
  final String mimeType;
  final bool encrypted;

  const ManifestInfo({
    required this.sessionId,
    required this.k,
    required this.blockLen,
    required this.totalLen,
    required this.frameBytes,
    required this.qrVersion,
    required this.mode,
    required this.fileName,
    required this.mimeType,
    required this.encrypted,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      k.hashCode ^
      blockLen.hashCode ^
      totalLen.hashCode ^
      frameBytes.hashCode ^
      qrVersion.hashCode ^
      mode.hashCode ^
      fileName.hashCode ^
      mimeType.hashCode ^
      encrypted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ManifestInfo &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          k == other.k &&
          blockLen == other.blockLen &&
          totalLen == other.totalLen &&
          frameBytes == other.frameBytes &&
          qrVersion == other.qrVersion &&
          mode == other.mode &&
          fileName == other.fileName &&
          mimeType == other.mimeType &&
          encrypted == other.encrypted;
}

/// The user-visible file recovered from a DCF3 container.
class OpticalFileData {
  final String name;
  final String mimeType;
  final Uint8List bytes;

  /// BLAKE3 digest of the original bytes (32 bytes).
  final Uint8List digest;
  final String compression;
  final bool encrypted;
  final int transmittedSize;

  const OpticalFileData({
    required this.name,
    required this.mimeType,
    required this.bytes,
    required this.digest,
    required this.compression,
    required this.encrypted,
    required this.transmittedSize,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      mimeType.hashCode ^
      bytes.hashCode ^
      digest.hashCode ^
      compression.hashCode ^
      encrypted.hashCode ^
      transmittedSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpticalFileData &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          mimeType == other.mimeType &&
          bytes == other.bytes &&
          digest == other.digest &&
          compression == other.compression &&
          encrypted == other.encrypted &&
          transmittedSize == other.transmittedSize;
}

/// A DCF3 container as produced by the sender-side packing.
class PackedFileData {
  final Uint8List container;
  final int originalSize;
  final int transmittedSize;

  /// `"gzip"` or `"none"`.
  final String compression;
  final bool encrypted;

  const PackedFileData({
    required this.container,
    required this.originalSize,
    required this.transmittedSize,
    required this.compression,
    required this.encrypted,
  });

  @override
  int get hashCode =>
      container.hashCode ^
      originalSize.hashCode ^
      transmittedSize.hashCode ^
      compression.hashCode ^
      encrypted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PackedFileData &&
          runtimeType == other.runtimeType &&
          container == other.container &&
          originalSize == other.originalSize &&
          transmittedSize == other.transmittedSize &&
          compression == other.compression &&
          encrypted == other.encrypted;
}

/// Result of pushing one decoded frame into a receiving session.
enum PushStatus {
  /// Frame passed integrity checks and was folded into the decoder.
  accepted,

  /// Frame was damaged, duplicated, or the transfer already completed.
  ignored,

  /// The whole payload was recovered.
  complete,
}

class QrDecodeResult {
  final Uint8List? bytes;
  final QrTrackerState tracker;

  const QrDecodeResult({this.bytes, required this.tracker});

  @override
  int get hashCode => bytes.hashCode ^ tracker.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QrDecodeResult &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          tracker == other.tracker;
}

/// A QR symbol as a binary module matrix.
///
/// `cells` is row-major and holds `width * height` entries, each `0` (light)
/// or `1` (dark). Flutter renders it by scaling to the target rectangle.
class QrMatrix {
  final int width;
  final int height;
  final Uint8List cells;

  const QrMatrix({
    required this.width,
    required this.height,
    required this.cells,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ cells.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QrMatrix &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          cells == other.cells;
}

/// Temporal QR tracker state, updated functionally across frames.
///
/// After the first successful decode the tracker remembers where the symbol
/// was and only searches a small region of interest around it for the next
/// frames, falling back to a full-frame search only after consecutive misses.
/// The receiver feeds the returned state back on every frame, so no global
/// mutable state is needed and the bridge stays stateless.
class QrTrackerState {
  final bool active;
  final int x0;
  final int y0;
  final int x1;
  final int y1;
  final int hits;
  final int failures;
  final int qrVersion;
  final int lastThreshold;

  const QrTrackerState.raw({
    required this.active,
    required this.x0,
    required this.y0,
    required this.x1,
    required this.y1,
    required this.hits,
    required this.failures,
    required this.qrVersion,
    required this.lastThreshold,
  });

  static QrTrackerState default_() =>
      RustLib.instance.api.crateApiTypesQrTrackerStateDefault();

  /// A fresh, inactive tracker.
  factory QrTrackerState() =>
      RustLib.instance.api.crateApiTypesQrTrackerStateNew();

  @override
  int get hashCode =>
      active.hashCode ^
      x0.hashCode ^
      y0.hashCode ^
      x1.hashCode ^
      y1.hashCode ^
      hits.hashCode ^
      failures.hashCode ^
      qrVersion.hashCode ^
      lastThreshold.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QrTrackerState &&
          runtimeType == other.runtimeType &&
          active == other.active &&
          x0 == other.x0 &&
          y0 == other.y0 &&
          x1 == other.x1 &&
          y1 == other.y1 &&
          hits == other.hits &&
          failures == other.failures &&
          qrVersion == other.qrVersion &&
          lastThreshold == other.lastThreshold;
}

/// Outcome of one `receiver_push` call, carrying live session state so the UI
/// can render progress without a second round trip.
class ReceiverOutcome {
  final PushStatus status;

  /// Recovered DCF3 container when `status == Complete`.
  final Uint8List? container;

  /// Distinct frames accepted so far (drives the progress bar).
  final int collected;
  final int? k;
  final int? blockLen;
  final int? totalLen;
  final int? sessionId;
  final String? mode;
  final bool delivered;

  const ReceiverOutcome({
    required this.status,
    this.container,
    required this.collected,
    this.k,
    this.blockLen,
    this.totalLen,
    this.sessionId,
    this.mode,
    required this.delivered,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      container.hashCode ^
      collected.hashCode ^
      k.hashCode ^
      blockLen.hashCode ^
      totalLen.hashCode ^
      sessionId.hashCode ^
      mode.hashCode ^
      delivered.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReceiverOutcome &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          container == other.container &&
          collected == other.collected &&
          k == other.k &&
          blockLen == other.blockLen &&
          totalLen == other.totalLen &&
          sessionId == other.sessionId &&
          mode == other.mode &&
          delivered == other.delivered;
}

/// One emitted fountain frame: the self-describing wire bytes.
class SenderFrame {
  /// Sequence number (also embedded in `bytes`).
  final int seq;

  /// Complete frame bytes: 25-byte protocol header + payload block.
  final Uint8List bytes;

  const SenderFrame({required this.seq, required this.bytes});

  @override
  int get hashCode => seq.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SenderFrame &&
          runtimeType == other.runtimeType &&
          seq == other.seq &&
          bytes == other.bytes;
}

/// A fountain frame together with its QR rendering, produced in one FFI call
/// so the sender loop crosses the bridge only once per frame.
class SenderFrameQr {
  final SenderFrame frame;
  final QrMatrix qr;

  const SenderFrameQr({required this.frame, required this.qr});

  @override
  int get hashCode => frame.hashCode ^ qr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SenderFrameQr &&
          runtimeType == other.runtimeType &&
          frame == other.frame &&
          qr == other.qr;
}

/// Static facts about a live sending session (all constant across a stream).
class SenderInfo {
  final int sessionId;

  /// Source block count.
  final int k;

  /// Payload bytes per frame (frame size minus the 25-byte header).
  final int blockLen;

  /// Protected container length in bytes.
  final int totalLen;

  /// Transmission mode: `"causal"`, `"systematic"` or `"rsd"`.
  final String mode;

  /// Total bytes per frame on the wire (header + block).
  final int frameBytes;

  /// QR version (1..=40) used to carry one frame.
  final int qrVersion;

  const SenderInfo({
    required this.sessionId,
    required this.k,
    required this.blockLen,
    required this.totalLen,
    required this.mode,
    required this.frameBytes,
    required this.qrVersion,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      k.hashCode ^
      blockLen.hashCode ^
      totalLen.hashCode ^
      mode.hashCode ^
      frameBytes.hashCode ^
      qrVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SenderInfo &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          k == other.k &&
          blockLen == other.blockLen &&
          totalLen == other.totalLen &&
          mode == other.mode &&
          frameBytes == other.frameBytes &&
          qrVersion == other.qrVersion;
}
